### ISSUE TITLE
transfer ownership?

### ISSUE THREAD

**Issue by tkellen** [SE7ENSKY/require-stylus#2]
Would you be willing to transfer ownership of this repo to myself or @mzgoddard?  We're planning on building this out further in the coming weeks and it seems as though this project has been abandoned?

**Comment by ivankravchenko** [comment]
Hey guys, I will add you as collaborators, so you have appropriate access.
Interesting, What is your roadmap?

**Comment by tkellen** [comment]
I don't have specifics just yet, but we'll stay in touch as we get started!
